Name:           ros-indigo-ps3joy
Version:        1.10.0
Release:        0%{?dist}
Summary:        ROS ps3joy package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/ps3joy
Source0:        %{name}-%{version}.tar.gz

Requires:       bluez-libs
Requires:       libusb-devel
Requires:       linuxconsoletools
Requires:       pybluez
Requires:       ros-indigo-diagnostic-msgs
Requires:       ros-indigo-rosgraph
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
BuildRequires:  bluez-libs
BuildRequires:  libusb-devel
BuildRequires:  linuxconsoletools
BuildRequires:  pybluez
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-diagnostic-msgs
BuildRequires:  ros-indigo-rosgraph
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-sensor-msgs

%description
Playstation 3 SIXAXIS or DUAL SHOCK 3 joystick driver. Driver for the Sony
PlayStation 3 SIXAXIS or DUAL SHOCK 3 joysticks. In its current state, this
driver is not compatible with the use of other Bluetooth HID devices. The driver
listens for a connection on the HID ports, starts the joystick streaming data,
and passes the data to the Linux uinput device so that it shows up as a normal
joystick.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Jonathan Bohren <jbo@jhu.edu> - 1.10.0-0
- Autogenerated by Bloom

